name:                authra
version:             0.1.0.0
github:              "githubuser/authra"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/authra#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- formatting
- prosumma
- rio
- servant
- servant-auth
- servant-auth-server
- servant-server
- uuid
- wai
- warp

default-extensions:
- NoImplicitPrelude
- FlexibleInstances
- MultiParamTypeClasses
- OverloadedStrings
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  authra-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - authra

tests:
  authra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - authra
